services:
  # Main service: PostgreSQL with pgVector extension
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_rag_ts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      # Data persistence
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Checks if the database is ready
      test: ["CMD-SHELL", "pg_isready -U postgres -d rag"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Auxiliary service: Initializes pgVector extension
  bootstrap_vector_ext:
    image: pgvector/pgvector:pg17
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      PGPASSWORD=postgres
      psql "postgresql://postgres@postgres:5432/rag" -v ON_ERROR_STOP=1
      -c "CREATE EXTENSION IF NOT EXISTS vector;"
    restart: "no"

volumes:
  postgres_data: